web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
        - db
php:
    image: php:7.2-fpm
    volumes:
        - ./code:/code

db:
    image: mysql:5.7
