# This aims to be a standard compose for a php-project (magento in mind)
# Author: Navalona Ramanantoanina <job.navds@gmail.com>
#

version: '2'
services:
    php:
        image: navds-php
        build:
            context: ./custom_images/php
            args:
                version: "7.1"
        volumes:
            - ./code:/code

    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=changeme
        volumes:
            - ./persistence/mysql:/var/lib/mysql

    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
            - db
